---
title: "spl"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(entropy)
library(scales)
library(ggunchained)
```

D41 (NTR scroes with metadata)
```{r}
# ntr_paths = list.files("deu/data/ntr_out", pattern = "*.csv", full.names = T)
# 
# norm41 = read_csv(ntr_paths[str_detect(ntr_paths, "41")]) %>%
#   rename(rowname = doc_id)
# 
# meta_data = read_csv("deu/data/02_deu_raw.csv")
# 
# D41 = left_join(norm41, meta_data, by = "rowname")
# rm(norm41, meta_data)
```


Document topic composition
```{r}
z <- function(d) (d - mean(d)) / sd(d)

calculate_entropy <- function(path) {
  
  document_topic = read_csv(path)
  
  doc_id = document_topic %>%
    select(doc_id)
  
  document_topic = document_topic %>%
    select(-doc_id) %>%
    as.matrix(., ncol = 100)

  entropy_df = doc_id %>%
    mutate(H = apply(document_topic, 1, entropy.plugin, unit = "log2")) %>%
    mutate(z_H = z(H))
  
  return(entropy_df)
}

H_fr = calculate_entropy("fra/data/fra_ntr_in.csv")
H_de = calculate_entropy("deu/data/deu_ntr_in.csv")
```

Speech length
```{r}
D41 = read_csv("deu/data/D41.csv") %>%
  rename(doc_id = rowname) %>%
  mutate(n_word = str_count(text_c, pattern = "\\S+")) %>%
  right_join(H_de, by = "doc_id")
```

Plots
```{r}
D41 %>%
  # NAs in text_c
  filter(!is.na(text_c)) %>%
  # smaller speeches
  filter(n_word <= 250) %>%
  ggplot(aes(n_word, z_H)) +
  geom_bin2d(bins = 100) +
  scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000),
                       labels = trans_format("log10", 
                                             math_format(expr = 10^.x, format = force))) +
  theme_janco_point() +
  theme(legend.direction = "vertical", legend.position = "right",
        plot.caption = element_text(hjust = 0.5)) +
  labs(fill = "speech count",
       x = "number of words",
       y = "z-scaled H(X)",
       subtitle = "Speech length vs. entropy 
       \n(Bundestag, for speeches shorter than 250 words)")
  
  
  # ggplot(aes(n_word, z_H)) +
  #   geom_bin2d(bins = 100) +
  #   scale_fill_viridis_c(trans = "log", breaks = c(1,10,100,1000),
  #                        labels = trans_format("log10", 
  #                                              math_format(expr = 10^.x, format = force))) +
  #   # geom_smooth(method = "lm", colour = "black", alpha = 0, size = 0.5) +
  #   # labs(x = "Novelty (z-scaled)\n", y = "Resonance (z-scaled)", 
  #   #      title = paste0("Resonance vs. Novelty, w = ", w),
  #   #      subtitle = "with a regression line",
  #   #      caption = "Data source: Bundestag debates (1998-2019)",
  #   #      fill = "speech\ncount") +
  #   # scale_x_continuous(breaks = seq(-4, 8, 2)) +
  #   # scale_y_continuous(breaks = seq(-6, 6, 2)) +
  #   # theme_janco_point() +
  #   theme(legend.direction = "vertical", legend.position = "right",
  #         plot.caption = element_text(hjust = 0.5)
  #   ) #+
  #   #coord_fixed()

D41 %>%
  # NAs in text_c
  filter(!is.na(text_c)) %>%
  # smaller speeches
  filter(n_word <= 500) %>%
  # filter presidential
  filter(role != "presidency") %>%
  # plot
  ggplot(aes(n_word, z_H)) +
  geom_jitter(alpha = 0.05) +
  theme_janco_point() +
  theme(legend.direction = "vertical", legend.position = "right",
        plot.caption = element_text(hjust = 0.5)) +
  labs(x = "number of words",
       y = "z-scaled H(X)",
       subtitle = "Speech length (<501 words) vs. entropy of topic distributions 
       \n(Bundestag, presidential speeches removed)")

D41 %>%
  # NAs in text_c
  filter(!is.na(text_c)) %>%
  # smaller speeches
  filter(n_word <= 3000) %>%
  # presidential dummy
  mutate(presidential = ifelse(role == "presidency", "presidential", "other")) %>%
  # plot
  ggplot(aes(n_word, z_H, color = factor(presidential))) +
  geom_jitter(alpha = 0.05) +
  theme_janco_point() +
  theme(legend.direction = "vertical", legend.position = "right",
        plot.caption = element_text(hjust = 0.5)) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  labs(x = "number of words",
       y = "z-scaled H(X)",
       subtitle = "Speech length (<3001 words) vs. entropy of topic distributions 
       \n(Bundestag, presidential and regular speeches)",
       color = "speech category")
```

